name: Jekyll site CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest 

    steps: 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Chrome Driver
      uses: nanasess/setup-chromedriver@v1
      with:
        chromedriver-version: latest

    - name: Run Tests
      run: mvn test
      continue-on-error: true
